apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-argocd-kasten-secret
  namespace: {{ .Values.argocdNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-argocd-kasten-secret
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
