apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-tanzukubernetescluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-tanzukubernetescluster
subjects:
- kind: ServiceAccount
  name: default
  namespace: argocd
