apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{.Release.Name}}-pinniped-controller
  name: {{.Release.Name}}-pinniped-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Release.Name}}-pinniped-controller
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{.Release.Name}}-pinniped-controller
    spec:
      containers:
      - name: {{.Release.Name}}-pinniped-controller
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources: {}
        env:
        - name: ARGOCD_NAMESPACE
          value: {{ .Values.argocdNamespace }}
        - name: INSTALL_VERSION
          value: "{{ .Values.pinnipedVersion }}"
        - name: REQUIRED_LABEL
          value: "{{ .Values.requiredLabel }}"
        - name: ENABLE_INDEX
          value: "{{ .Values.enableIndex }}"
        {{- if .Values.env }}
        {{- include "common.tplvalues.render" (dict "value" .Values.env "context" $) | nindent 8 }}
        {{- end }}
        {{- if .Values.persistence.enabled }}
        volumeMounts:
          - name: {{.Release.Name}}-pinniped
            mountPath: /opt/www
          {{- if .Values.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- end }}
      volumes:
        - name: {{.Release.Name}}-pinniped
          persistentVolumeClaim:
            claimName: {{.Release.Name}}-pinniped
        {{- if .Values.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
status: {}
