apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: argocd-pinniped-controller
  name: argocd-pinniped
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: argocd-pinniped-controller
