apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-capi-watch
  namespace: {{ .Values.register.argocdNamespace }}
rules:
- apiGroups:
  - "cluster.x-k8s.io"
  resources:
  - "clusters"
  verbs:
  - get
  - list
  - watch
