apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-argocd-exec
  namespace: {{ .Values.register.argocdNamespace }}
rules:
- apiGroups:
  - ""
  resources:
  - "*"
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - get 
  - create
