apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-argocd-labels-secret
  namespace: {{ .Values.argocdNamespace }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - update
  - patch
  - delete
  - watch
