apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{.Release.Name}}-sync-labels-controller
  name: {{.Release.Name}}-sync-labels
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{.Release.Name}}-sync-labels-controller
